### ISSUE TITLE
Present Project

### ISSUE THREAD

**Issue by o0Mink0o** [seroseeisero/Bc-pj14#1]
เนืื้อเรื่อง และ Game play

- โอ๊ตมีหน้าที่ Manager และเป็นคน suport เรื่องต่างๆ

-มิ้งค์มีหน้าที่เขียนcode และ Designer รูปเกม

-ป๋องมีหน้าที่Designer ตัวละครเกม และเขียนcode

**Comment by OatPakin** [comment]
หัวข้อโครงงานคือ เกม Tap to graduation

theme ของเกม วิชาเรียนของเด็ก ปี 1

ตัวละครหลัก มี Oat Pong Ming

ฉากเกม มหาวิทยาลัยเชี่ยงใหม่
