### ISSUE TITLE
✅หน้าเลือกตัวละคร

### ISSUE THREAD

**Issue by o0Mink0o** [seroseeisero/Bc-pj14#18]
✅-มีให้เลือกตัวละคร**แต่พอกดเป็นการสุ่มจาก3ตัว** (ป๋องรับผิดชอบ)
   -พื้นหลังสำหรับเลือกตัวละคร
   -ตัวละครอีก3ตัว
       -เป็นพวกเรา3แต่เปลี่ยนเครื่องแต่งกาย 

-เขียนcodeเข้าหน้าเลือดตัวละคร(มิ้งค์)

**Comment by OatPakin** [comment]
เพิ่มเสียงเอฟเฟคเขาไปในเกม

https://youtu.be/-D2iL1GYdx0?si=d5F9kuUu4W38Y70T

**Comment by o0Mink0o** [comment]
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/1d45a642-3370-4ecb-b868-a929b5b6fe8c)
