### ISSUE TITLE
หน้าเริ่มเกมโดยรวม

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#19]
[https://o365cmu-my.sharepoint.com/personal/phirapart_yangna_cmu_ac_th/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fphirapart%5Fyangna%5Fcmu%5Fac%5Fth%2FDocuments%2Ftttg%2FTAP%20TO%20GRADUATION%2F%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B9%80%E0%B8%A3%E0%B8%B4%E0%B9%88%E0%B8%A1%E0%B9%80%E0%B8%81%E0%B8%A1%2F%E0%B8%9B%E0%B8%B8%E0%B9%88%E0%B8%A1%E0%B9%80%E0%B8%A5%E0%B9%88%E0%B8%99](url)

**Comment by o0Mink0o** [comment]
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/a91e6546-f21b-4bd4-a31e-1961e609d9c8)

**Comment by o0Mink0o** [comment]
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/7a3e4ee7-dc19-47df-9dff-f404b6e4e17e)

**Comment by o0Mink0o** [comment]
ยังขาดชื่อเกม
