### ISSUE TITLE
✅ฉากหลังหน้าเปิดเกม

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#20]

**Comment by o0Mink0o** [comment]
![พื้นหลังหน้าเลือกตัวละคร](https://github.com/seroseeisero/Bc-pj14/assets/141802449/e04af0cd-71ed-4f9a-bcf3-06d636373567)

**Comment by o0Mink0o** [comment]
![พื้นหลังหน้าเริ่มเกม](https://github.com/seroseeisero/Bc-pj14/assets/141802449/c0cd179e-1dcb-4068-87b8-810caad3fb33)
