### ISSUE TITLE
✅อนิเมชั่นตัวละครหน้าเกม

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#21]
- [ การขยับตัวละคร ] 

- [codeให้ตัวละครทำการขยับ ]

**Comment by o0Mink0o** [comment]
![Untitled_Artwork-1](https://github.com/seroseeisero/Bc-pj14/assets/141802449/d30afeb5-b78e-4f31-bcf9-1d566d601011)

**Comment by o0Mink0o** [comment]
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/ec61a12d-9ec0-4300-9d4c-ce8403f311aa)
