### ISSUE TITLE
✅ปุ่มplay

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#22]
- [ การขยับเมื่อเมาส์ไปแตะ ] ✅

- [ กดเข้าเกม ] ✅

**Comment by o0Mink0o** [comment]
![Uploading Untitled_Artwork-2.PNG…]()

**Comment by o0Mink0o** [comment]
![Untitled_Artwork-2](https://github.com/seroseeisero/Bc-pj14/assets/141802449/75b0f65c-8854-43ce-b31d-183515cc29a1)
