### ISSUE TITLE
✅อนิเมชั่นกระเป๋าหน้าเกม

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#23]
เป็นการเอาเมาส์ไปชี้แล้วขยับเปิด-ปิด

**Comment by o0Mink0o** [comment]
![1](https://github.com/seroseeisero/Bc-pj14/assets/141802449/add84bbc-53be-467c-ad76-2cd677d20808)

**Comment by o0Mink0o** [comment]
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/b26bc0ad-9a09-4df6-800b-be77a433d340)
