### ISSUE TITLE
✅ประโยคบอกให้เลือกตัว

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#24]
- อนิเมชั่นการขยับ

**Comment by o0Mink0o** [comment]
![Uploading Untitled_Artwork-1.PNG…]()

**Comment by o0Mink0o** [comment]
![Untitled_Artwork-1](https://github.com/seroseeisero/Bc-pj14/assets/141802449/9ffc534a-88bb-4381-b090-82adaa687cd4)
