### ISSUE TITLE
✅อนิเมชั่นโอ๊ต

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#28]
- การขยับ✅
- เมื่อกดเข้าไปจะอธิบาย✅

**Comment by o0Mink0o** [comment]
![Uploading image.png…]()

**Comment by o0Mink0o** [comment]
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/b801a96a-efc1-4a73-8fad-c3360010902e)
