### ISSUE TITLE
✅คำอธิบายตัวละคร

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#30]
- อธิบายเกี่ยวกับค่าพลัง ชื่อ ต่างๆ✅

**Comment by o0Mink0o** [comment]
![20230903_111754000_iOS](https://github.com/seroseeisero/Bc-pj14/assets/141802449/94c24b80-0dc6-4602-91da-6aa97bebd803)
![20230903_111754000_iOS 1](https://github.com/seroseeisero/Bc-pj14/assets/141802449/5d4eebc9-b23e-4870-9ca8-a08d7cb72a10)
![20230903_111754000_iOS 2](https://github.com/seroseeisero/Bc-pj14/assets/141802449/9bef5c19-6415-44bd-a068-2f05a68e4530)

**Comment by seroseeisero** [comment]
![1](https://github.com/seroseeisero/Bc-pj14/assets/141814539/940d6edb-5c5d-4650-aa36-6c784d0317ea)
![2](https://github.com/seroseeisero/Bc-pj14/assets/141814539/84533b61-70ad-4b6d-a9c2-dea665995c42)
![3](https://github.com/seroseeisero/Bc-pj14/assets/141814539/130c5d58-26fc-47d4-8c77-58455ef98ae8)
