### ISSUE TITLE
✅การสุ่ม

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#31]
เป็นการแบบสุ่มตัวลรที่กดแล้วจะสุ่ม 2ตัวที่ไม่ใช่ตัวที่เลือก✅

**Comment by o0Mink0o** [comment]
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/b1b8b697-2580-4735-85ed-2d2018987d92)
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/7cd75ef1-42c0-4d9f-b587-dc5947d4e35d)
