### ISSUE TITLE
✅ฉากเลือกด่าน

### ISSUE THREAD

**Issue by OatPakin** [seroseeisero/Bc-pj14#33]
- มี5ด่าน ✅

**Comment by o0Mink0o** [comment]
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/551a2c76-666d-418e-bb3d-4bc1786479ac)
![image](https://github.com/seroseeisero/Bc-pj14/assets/141802449/31f4175a-978f-4de7-8bd7-2af113ea3c57)
