### ISSUE TITLE
แก้ปรับภาพให้ชัดเจน

### ISSUE THREAD

**Issue by o0Mink0o** [seroseeisero/Bc-pj14#38]
ตรงอธิบาย

**Comment by seroseeisero** [comment]
![1](https://github.com/seroseeisero/Bc-pj14/assets/141814539/2dcf4a3f-3a28-43f8-8e27-c001f4f28060)
![2](https://github.com/seroseeisero/Bc-pj14/assets/141814539/702206c3-dc8c-4918-b88e-1421e7acd199)
![3](https://github.com/seroseeisero/Bc-pj14/assets/141814539/9f663d13-26a5-4601-9607-3ca8e11fee68)
ภาพแตกที่แก้ไขแล้ว
